# Generated by Django 5.2.6 on 2025-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=2, upload_to='uploads/avatars'),
            preserve_default=False,
        ),
    ]
